import { useDeferredValue, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, Boxes, Cpu, Hourglass, Pencil, Plus, Ship, Thermometer, Timer, Trash2 } from 'lucide-react'

import { Appear } from '@/components/appear.jsx'
import { ListToolbar } from '@/components/list-toolbar.jsx'
import { PageHeader } from '@/components/page-header.jsx'
import { StatusBadge } from '@/components/status-badge.jsx'
import { Button } from '@/components/ui/button.jsx'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog.jsx'
import { Input } from '@/components/ui/input.jsx'
import { Label } from '@/components/ui/label.jsx'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select.jsx'
import { apiError, batchInputSchema, deleteBatch, listBatches, listFishingTrips, saveBatch, simulateBatchQualityRisk } from './batches-api.js'

const statusLabels = { MONITORING: 'Dipantau', ACTIVE: 'Aktif', INSPECTION_HOLD: 'Ditahan untuk pemeriksaan', HANDED_OVER: 'Diserahkan', CLOSED: 'Ditutup' }
const statusTones = { MONITORING: 'neutral', ACTIVE: 'healthy', INSPECTION_HOLD: 'warning', HANDED_OVER: 'neutral', CLOSED: 'neutral' }
const sortOptions = [{ value: 'code', label: 'ID batch' }, { value: 'currentTemperatureC', label: 'Suhu' }, { value: 'remainingQualityWindowDays', label: 'Sisa mutu' }, { value: 'receivedAt', label: 'Tanggal diterima' }, { value: 'weightKg', label: 'Berat' }, { value: 'grade', label: 'Mutu' }]
const localValue = (value) => new Date(value).toISOString().slice(0, 16)
const measurement = (value, suffix, maximumFractionDigits = 2) => value === null ? 'Tidak tersedia' : `${value.toLocaleString('id-ID', { maximumFractionDigits })}${suffix}`
const dateTime = (value) => new Date(value).toLocaleString('id-ID', { dateStyle: 'medium', timeStyle: 'short' })
function Field({ label, error, children }) { return <div className="grid gap-2"><Label className="text-xs font-semibold text-slate-600">{label}</Label>{children}{error && <span className="text-xs text-red-700">{error}</span>}</div> }
function ErrorMessage({ error }) { return <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700" role="alert">{apiError(error)}</p> }

function BatchDialog({ batch, trips, onClose }) {
  const queryClient = useQueryClient(); const [errors, setErrors] = useState({}); const mutation = useMutation({ mutationFn: (input) => saveBatch({ ...input, id: batch?.id }), onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['batches'] }), queryClient.invalidateQueries({ queryKey: ['fishing-trips'] }), queryClient.invalidateQueries({ queryKey: ['overview'] }), queryClient.invalidateQueries({ queryKey: ['resources'] })]); onClose() } })
  function submit(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const result = batchInputSchema.safeParse({ code: form.get('code'), fishingTripId: form.get('fishingTripId'), weightKg: Number(form.get('weightKg')), grade: form.get('grade'), receivedAt: new Date(form.get('receivedAt')).toISOString() }); if (!result.success) return setErrors(Object.fromEntries(result.error.issues.map((issue) => [issue.path[0], issue.message]))); setErrors({}); mutation.mutate(result.data) }
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="max-w-[520px] p-6"><form className="grid gap-4" onSubmit={submit}><DialogHeader><DialogTitle>{batch ? 'Edit batch' : 'Terima batch'}</DialogTitle><DialogDescription className="sr-only">Detail penerimaan batch</DialogDescription></DialogHeader><Field label="ID batch" error={errors.code}><Input name="code" defaultValue={batch?.code ?? ''} placeholder="B-017" autoFocus required /></Field><div className="grid grid-cols-2 gap-3"><Field label="Berat (kg)" error={errors.weightKg}><Input name="weightKg" type="number" min="0.01" step="0.01" defaultValue={batch?.weightKg ?? ''} required /></Field><Field label="Mutu" error={errors.grade}><Input name="grade" defaultValue={batch?.grade ?? ''} required /></Field></div><Field label="Perjalanan melaut" error={errors.fishingTripId}><Select name="fishingTripId" defaultValue={batch?.fishingTripId ?? trips[0]?.id}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{trips.map((trip) => <SelectItem key={trip.id} value={trip.id}>{trip.code} · {trip.vesselName}</SelectItem>)}</SelectContent></Select></Field><Field label="Tanggal diterima" error={errors.receivedAt}><Input name="receivedAt" type="datetime-local" defaultValue={localValue(batch?.receivedAt ?? new Date())} required /></Field>{mutation.isError && <ErrorMessage error={mutation.error} />}<DialogFooter><Button variant="outline" type="button" onClick={onClose}>Batal</Button><Button disabled={mutation.isPending}>{mutation.isPending ? 'Menyimpan…' : batch ? 'Simpan batch' : 'Terima batch'}</Button></DialogFooter></form></DialogContent></Dialog>
}

function DeleteDialog({ batch, onClose }) { const queryClient = useQueryClient(); const mutation = useMutation({ mutationFn: () => deleteBatch(batch.id), onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['batches'] }), queryClient.invalidateQueries({ queryKey: ['fishing-trips'] }), queryClient.invalidateQueries({ queryKey: ['overview'] }), queryClient.invalidateQueries({ queryKey: ['resources'] })]); onClose() } }); return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="max-w-[460px] p-6"><DialogHeader><DialogTitle>Hapus {batch.code}?</DialogTitle><DialogDescription>Batch akan dihapus dari catatan aktif. Riwayat operasionalnya tetap disimpan dan penugasan sensor yang aktif akan diakhiri.</DialogDescription></DialogHeader>{mutation.isError && <ErrorMessage error={mutation.error} />}<DialogFooter><Button variant="outline" onClick={onClose}>Batal</Button><Button variant="destructive" onClick={() => mutation.mutate()} disabled={mutation.isPending}><Trash2 />{mutation.isPending ? 'Menghapus…' : 'Hapus batch'}</Button></DialogFooter></DialogContent></Dialog> }

function BatchCard({ batch, onEdit, onDelete }) { const queryClient = useQueryClient(); const qualityRisk = useMutation({ mutationFn: () => simulateBatchQualityRisk(batch.id), onSuccess: () => Promise.all(['batches', 'overview', 'plans', 'resources'].map((queryKey) => queryClient.invalidateQueries({ queryKey: [queryKey] }))) }); const demoActive = batch.activeSensor?.code.startsWith('SIM-S-') && ['MONITORING', 'ACTIVE'].includes(batch.status); return <article className="flex flex-col rounded-xl border border-border bg-card p-5 shadow-[0_1px_2px_rgb(2_40_88_/_3%)]" data-batch-card><div className="flex items-start justify-between gap-4"><div><h2 className="text-base font-bold">{batch.code}</h2><p className="mt-1 text-xs text-muted-foreground">{batch.weightKg.toLocaleString('id-ID')} kg · Mutu {batch.grade}</p></div><StatusBadge tone={statusTones[batch.status]}>{statusLabels[batch.status]}</StatusBadge></div><div className="mt-5 grid grid-cols-3 divide-x divide-border border-y border-border py-4"><Metric icon={Thermometer} label="Suhu" value={measurement(batch.currentTemperatureC, '°C', 1)} /><Metric icon={Hourglass} label="Usia mutu" value={measurement(batch.equivalentQualityAgeDays, ' hari')} /><Metric icon={Timer} label="Sisa mutu" value={measurement(batch.remainingQualityWindowDays, ' hari')} /></div>{batch.qualityEstimateStartedAt && <p className="mt-3 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-[11px] leading-relaxed text-amber-800">Perkiraan mutu dihitung sejak waktu pemantauan pertama. <time dateTime={batch.qualityEstimateStartedAt}>{dateTime(batch.qualityEstimateStartedAt)}</time></p>}<dl className="mt-4 grid gap-2.5 text-xs"><Fact icon={Ship} label="Asal" value={`${batch.fishingTrip.code} · ${batch.fishingTrip.vesselName}`} /><Fact icon={Cpu} label="Sensor" value={batch.activeSensor?.code ?? 'Belum ditugaskan'} /></dl><time className="mt-5 text-[11px] text-muted-foreground">Diterima {dateTime(batch.receivedAt)}</time>{qualityRisk.isError && <ErrorMessage error={qualityRisk.error} />}{qualityRisk.isSuccess && <p className="mt-3 text-xs font-medium text-amber-800" role="status">Risiko mutu untuk {batch.code} berhasil disimulasikan</p>}<div className="mt-auto grid grid-cols-2 gap-2 pt-4">{demoActive && <Button className="col-span-2 w-full" variant="outline" size="sm" type="button" onClick={() => qualityRisk.mutate()} disabled={qualityRisk.isPending}><AlertTriangle />{qualityRisk.isPending ? 'Menyimulasikan risiko mutu…' : 'Simulasikan risiko mutu'}</Button>}<Button variant="outline" size="sm" onClick={onEdit}><Pencil />Edit</Button><Button variant="destructive-outline" size="sm" onClick={onDelete}><Trash2 />Hapus</Button></div></article> }
function Metric({ icon: Icon, label, value }) { return <div className="px-4 first:pl-0 last:pr-0"><div className="flex items-center gap-1.5 text-[10px] text-muted-foreground"><Icon size={14} />{label}</div><strong className="mt-2 block text-sm">{value}</strong></div> }
function Fact({ icon: Icon, label, value }) { return <div className="flex min-w-0 items-center gap-2"><Icon className="shrink-0 text-muted-foreground" size={15} /><dt className="text-muted-foreground">{label}</dt><dd className="ml-auto min-w-0 truncate font-semibold" title={value}>{value}</dd></div> }
function State({ children, error }) { return <div className={`flex min-h-72 flex-col items-center justify-center gap-3 rounded-xl border border-dashed px-5 text-sm ${error ? 'border-red-200 bg-red-50/40 text-red-700' : 'border-slate-300 bg-white/50 text-muted-foreground'}`} role={error ? 'alert' : 'status'}><Boxes size={22} />{children}</div> }

function compare(left, right, direction) { if (left === null) return 1; if (right === null) return -1; const result = typeof left === 'number' ? left - right : String(left).localeCompare(String(right), 'id-ID', { numeric: true }); return direction === 'asc' ? result : -result }

export function BatchesPage() {
  const [editing, setEditing] = useState(undefined); const [deleting, setDeleting] = useState(null); const [search, setSearch] = useState(''); const [sort, setSort] = useState('receivedAt'); const [direction, setDirection] = useState('desc'); const deferredSearch = useDeferredValue(search.trim().toLowerCase()); const query = useQuery({ queryKey: ['batches'], queryFn: listBatches, refetchInterval: 15_000 }); const trips = useQuery({ queryKey: ['fishing-trips'], queryFn: listFishingTrips }); const batches = (query.data ?? []).filter((batch) => batch.code.toLowerCase().includes(deferredSearch)).toSorted((a, b) => compare(a[sort], b[sort], direction))
  return <div className="mx-auto w-full max-w-[1180px] px-8 pt-12 pb-7 max-[780px]:px-4 max-[780px]:py-6"><PageHeader title="Batch" description="Pantau batch yang diterima, kondisi mutu, dan cakupan sensor." action={<Button onClick={() => setEditing(null)} disabled={!trips.data?.length}><Plus />Terima batch</Button>} />{query.isSuccess && query.data.length > 0 && <ListToolbar query={search} onQueryChange={setSearch} sort={sort} onSortChange={setSort} direction={direction} onDirectionChange={setDirection} options={sortOptions} resultCount={batches.length} searchLabel="Cari berdasarkan ID batch" />}{query.isPending && <State>Memuat batch…</State>}{query.isError && <State error>{apiError(query.error)}</State>}{query.isSuccess && !query.data.length && <State>Belum ada batch</State>}{query.isSuccess && query.data.length > 0 && !batches.length && <State>Tidak ada batch yang cocok dengan “{search}”</State>}{batches.length > 0 && <Appear className="grid grid-cols-3 gap-3.5 max-[1020px]:grid-cols-2 max-[640px]:grid-cols-1" stagger="[data-batch-card]">{batches.map((batch) => <BatchCard key={batch.id} batch={batch} onEdit={() => setEditing(batch)} onDelete={() => setDeleting(batch)} />)}</Appear>}{trips.isSuccess && !trips.data.length && <p className="mt-4 text-xs text-muted-foreground">Tambahkan perjalanan melaut sebelum menerima batch.</p>}{editing !== undefined && trips.data?.length > 0 && <BatchDialog batch={editing} trips={trips.data} onClose={() => setEditing(undefined)} />}{deleting && <DeleteDialog batch={deleting} onClose={() => setDeleting(null)} />}</div>
}
