import { useDeferredValue, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Anchor, Boxes, Check, Clock3, Pencil, Plus, Trash2 } from 'lucide-react'

import { Appear } from '@/components/appear.jsx'
import { ListToolbar } from '@/components/list-toolbar.jsx'
import { PageHeader } from '@/components/page-header.jsx'
import { StatusBadge } from '@/components/status-badge.jsx'
import { Button } from '@/components/ui/button.jsx'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog.jsx'
import { Input } from '@/components/ui/input.jsx'
import { Label } from '@/components/ui/label.jsx'
import { apiError, completeFishingTrip, deleteFishingTrip, fishingTripInputSchema, listFishingTrips, saveFishingTrip } from './batches-api.js'

const dateTime = (value) => new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })
const sortOptions = [{ value: 'code', label: 'Trip ID' }, { value: 'vesselName', label: 'Vessel name' }, { value: 'startedAt', label: 'Start date' }, { value: 'endedAt', label: 'End date' }]

function Field({ label, error, children }) { return <div className="grid gap-2"><Label className="text-xs font-semibold text-slate-600">{label}</Label>{children}{error && <span className="text-xs text-red-700">{error}</span>}</div> }
function ErrorMessage({ error }) { return <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700" role="alert">{apiError(error)}</p> }

function TripDialog({ trip, onClose }) {
  const queryClient = useQueryClient(); const [errors, setErrors] = useState({})
  const mutation = useMutation({ mutationFn: (input) => saveFishingTrip({ ...input, id: trip?.id }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['fishing-trips'] }); onClose() } })
  function submit(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const result = fishingTripInputSchema.safeParse({ code: form.get('code'), vesselName: form.get('vesselName') }); if (!result.success) return setErrors(Object.fromEntries(result.error.issues.map((issue) => [issue.path[0], issue.message]))); setErrors({}); mutation.mutate(result.data) }
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="max-w-[500px] p-6"><form className="grid gap-4" onSubmit={submit}><DialogHeader><DialogTitle>{trip ? 'Edit fishing trip' : 'Add fishing trip'}</DialogTitle><DialogDescription className="sr-only">Fishing trip details</DialogDescription></DialogHeader><Field label="Trip ID" error={errors.code}><Input name="code" defaultValue={trip?.code ?? ''} placeholder="FT-001" autoFocus required /></Field><Field label="Vessel" error={errors.vesselName}><Input name="vesselName" defaultValue={trip?.vesselName ?? ''} required /></Field>{mutation.isError && <ErrorMessage error={mutation.error} />}<DialogFooter><Button variant="outline" type="button" onClick={onClose}>Cancel</Button><Button disabled={mutation.isPending}>{mutation.isPending ? 'Saving…' : 'Save trip'}</Button></DialogFooter></form></DialogContent></Dialog>
}

function ActionDialog({ trip, action, onClose }) {
  const queryClient = useQueryClient(); const deleting = action === 'delete'
  const mutation = useMutation({ mutationFn: () => deleting ? deleteFishingTrip(trip.id) : completeFishingTrip(trip.id), onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['fishing-trips'] }), queryClient.invalidateQueries({ queryKey: ['batches'] })]); onClose() } })
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="max-w-[460px] p-6"><DialogHeader><DialogTitle>{deleting ? `Delete ${trip.code}?` : `Complete ${trip.code}?`}</DialogTitle><DialogDescription>{deleting ? 'The trip will be removed from active records. Trips with received batches cannot be deleted.' : 'Completion time will be recorded now.'}</DialogDescription></DialogHeader>{mutation.isError && <ErrorMessage error={mutation.error} />}<DialogFooter><Button variant="outline" onClick={onClose}>Cancel</Button><Button variant={deleting ? 'destructive' : 'default'} onClick={() => mutation.mutate()} disabled={mutation.isPending}>{deleting ? <Trash2 /> : <Check />}{mutation.isPending ? (deleting ? 'Deleting…' : 'Completing…') : (deleting ? 'Delete trip' : 'Complete trip')}</Button></DialogFooter></DialogContent></Dialog>
}

function TripCard({ trip, onEdit, onComplete, onDelete }) { return <article className="flex flex-col rounded-xl border border-border bg-card p-5 shadow-[0_1px_2px_rgb(2_40_88_/_3%)]" data-trip-card><div className="flex items-start justify-between gap-4"><div className="min-w-0"><h2 className="truncate text-base font-bold">{trip.code}</h2><p className="mt-1 truncate text-xs text-muted-foreground">{trip.vesselName}</p></div><StatusBadge tone={trip.status === 'ACTIVE' ? 'healthy' : 'neutral'}>{trip.status === 'ACTIVE' ? 'Active' : 'Completed'}</StatusBadge></div><dl className="mt-5 divide-y divide-border border-y border-border"><Fact icon={Clock3} label="Started" value={dateTime(trip.startedAt)} /><Fact icon={Check} label="Ended" value={trip.endedAt ? dateTime(trip.endedAt) : 'In progress'} /><Fact icon={Boxes} label="Batches" value={trip.batchCount.toLocaleString()} /></dl><div className="mt-auto pt-4">{trip.status === 'ACTIVE' && <Button className="mb-2 w-full" size="sm" onClick={onComplete}><Check />Complete trip</Button>}<div className="grid grid-cols-2 gap-2"><Button variant="outline" size="sm" onClick={onEdit}><Pencil />Edit</Button><Button variant="destructive-outline" size="sm" onClick={onDelete}><Trash2 />Delete</Button></div></div></article> }
function Fact({ icon: Icon, label, value }) { return <div className="flex items-center gap-3 py-3 text-xs"><Icon className="shrink-0 text-muted-foreground" size={15} /><dt className="text-muted-foreground">{label}</dt><dd className="ml-auto text-right font-semibold text-foreground">{value}</dd></div> }
function State({ children, error }) { return <div className={`flex min-h-72 flex-col items-center justify-center gap-3 rounded-xl border border-dashed px-5 text-sm ${error ? 'border-red-200 bg-red-50/40 text-red-700' : 'border-slate-300 bg-white/50 text-muted-foreground'}`} role={error ? 'alert' : 'status'}><Anchor size={22} />{children}</div> }

export function FishingTripsPage() {
  const [editing, setEditing] = useState(undefined); const [action, setAction] = useState(null); const [search, setSearch] = useState(''); const [sort, setSort] = useState('startedAt'); const [direction, setDirection] = useState('desc'); const deferredSearch = useDeferredValue(search.trim().toLowerCase()); const query = useQuery({ queryKey: ['fishing-trips'], queryFn: listFishingTrips })
  const trips = (query.data ?? []).filter((trip) => trip.code.toLowerCase().includes(deferredSearch)).toSorted((a, b) => { const left = a[sort] ?? ''; const right = b[sort] ?? ''; return direction === 'asc' ? String(left).localeCompare(String(right), undefined, { numeric: true }) : String(right).localeCompare(String(left), undefined, { numeric: true }) })
  return <div className="mx-auto w-full max-w-[1180px] px-8 pt-12 pb-7 max-[780px]:px-4 max-[780px]:py-6"><PageHeader title="Fishing trips" description="Track vessel trips and the batches received from each landing." action={<Button onClick={() => setEditing(null)}><Plus />Add trip</Button>} />{query.isSuccess && query.data.length > 0 && <ListToolbar query={search} onQueryChange={setSearch} sort={sort} onSortChange={setSort} direction={direction} onDirectionChange={setDirection} options={sortOptions} resultCount={trips.length} searchLabel="Search by trip ID" />}{query.isPending && <State>Loading fishing trips…</State>}{query.isError && <State error>{apiError(query.error)}</State>}{query.isSuccess && !query.data.length && <State>No fishing trips</State>}{query.isSuccess && query.data.length > 0 && !trips.length && <State>No trips match “{search}”</State>}{trips.length > 0 && <Appear className="grid grid-cols-3 gap-3.5 max-[1020px]:grid-cols-2 max-[640px]:grid-cols-1" stagger="[data-trip-card]">{trips.map((trip) => <TripCard key={trip.id} trip={trip} onEdit={() => setEditing(trip)} onComplete={() => setAction({ trip, action: 'complete' })} onDelete={() => setAction({ trip, action: 'delete' })} />)}</Appear>}{editing !== undefined && <TripDialog trip={editing} onClose={() => setEditing(undefined)} />}{action && <ActionDialog {...action} onClose={() => setAction(null)} />}</div>
}
