import { useDeferredValue, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Anchor, Boxes, Check, Clock3, Pencil, Plus, Trash2 } from 'lucide-react'

import { Appear } from '@/components/appear.jsx'
import { ListToolbar } from '@/components/list-toolbar.jsx'
import { PageHeader } from '@/components/page-header.jsx'
import { StatusBadge } from '@/components/status-badge.jsx'
import { Button } from '@/components/ui/button.jsx'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog.jsx'
import { Input } from '@/components/ui/input.jsx'
import { Label } from '@/components/ui/label.jsx'
import { listResources } from '@/features/resources/resources-api.js'
import { apiError, completeFishingTrip, deleteFishingTrip, fishingTripInputSchema, listFishingTrips, saveFishingTrip } from './batches-api.js'

const dateTime = (value) => new Date(value).toLocaleString('id-ID', { dateStyle: 'medium', timeStyle: 'short' })
const sortOptions = [{ value: 'code', label: 'ID perjalanan' }, { value: 'vesselName', label: 'Nama kapal' }, { value: 'startedAt', label: 'Tanggal mulai' }, { value: 'endedAt', label: 'Tanggal selesai' }]

function Field({ label, error, htmlFor, children }) { return <div className="grid gap-2"><Label className="text-xs font-semibold text-slate-600" htmlFor={htmlFor}>{label}</Label>{children}{error && <span id={htmlFor ? `${htmlFor}-error` : undefined} className="text-xs text-red-700">{error}</span>}</div> }
function ErrorMessage({ error }) { return <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700" role="alert">{apiError(error)}</p> }

function TripDialog({ trip, onClose }) {
  const queryClient = useQueryClient(); const [errors, setErrors] = useState({})
  const mutation = useMutation({ mutationFn: (input) => saveFishingTrip({ ...input, id: trip?.id }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['fishing-trips'] }); onClose() } })
  function submit(event) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const result = fishingTripInputSchema.safeParse({ code: form.get('code'), vesselName: form.get('vesselName') }); if (!result.success) { setErrors(Object.fromEntries(result.error.issues.map((issue) => [issue.path[0], issue.message]))); requestAnimationFrame(() => formElement.querySelector('[aria-invalid="true"]')?.focus()); return } setErrors({}); mutation.mutate(result.data) }
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="max-w-[500px] p-6"><form className="grid gap-4" onSubmit={submit}><DialogHeader><DialogTitle>{trip ? 'Edit perjalanan melaut' : 'Tambah perjalanan melaut'}</DialogTitle><DialogDescription className="sr-only">Detail perjalanan melaut</DialogDescription></DialogHeader><Field label="ID perjalanan" htmlFor="trip-code" error={errors.code}><Input id="trip-code" name="code" defaultValue={trip?.code ?? ''} placeholder="FT-001" autoFocus required aria-invalid={Boolean(errors.code)} aria-describedby={errors.code ? 'trip-code-error' : undefined} /></Field><Field label="Nama kapal" htmlFor="vessel-name" error={errors.vesselName}><Input id="vessel-name" name="vesselName" defaultValue={trip?.vesselName ?? ''} required aria-invalid={Boolean(errors.vesselName)} aria-describedby={errors.vesselName ? 'vessel-name-error' : undefined} /></Field>{mutation.isError && <ErrorMessage error={mutation.error} />}<DialogFooter><Button variant="outline" type="button" onClick={onClose}>Batal</Button><Button disabled={mutation.isPending}>{mutation.isPending ? 'Menyimpan…' : 'Simpan perjalanan'}</Button></DialogFooter></form></DialogContent></Dialog>
}

function ActionDialog({ trip, action, onClose }) {
  const queryClient = useQueryClient(); const deleting = action === 'delete'; const [batches, setBatches] = useState([{ weightKg: '', grade: '', sensorId: '' }]); const sensors = useQuery({ queryKey: ['resources', 'sensors'], queryFn: () => listResources('sensors'), enabled: !deleting })
  const mutation = useMutation({ mutationFn: () => deleting ? deleteFishingTrip(trip.id) : completeFishingTrip(trip.id, batches.map((batch) => ({ ...batch, weightKg: Number(batch.weightKg) }))), onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['fishing-trips'] }), queryClient.invalidateQueries({ queryKey: ['batches'] }), queryClient.invalidateQueries({ queryKey: ['resources'] })]); onClose() } })
  const availableSensors = (sensors.data ?? []).filter((sensor) => sensor.status === 'AVAILABLE' && sensor.provisioningStatus === 'PROVISIONED')
  function update(index, field, value) { setBatches((current) => current.map((batch, candidate) => candidate === index ? { ...batch, [field]: value } : batch)) }
  const valid = deleting || batches.every((batch) => Number(batch.weightKg) > 0 && batch.grade.trim() && batch.sensorId) && new Set(batches.map(({ sensorId }) => sensorId)).size === batches.length
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="max-w-[620px] p-6"><DialogHeader><DialogTitle>{deleting ? `Hapus ${trip.code}?` : `Selesaikan pendaratan ${trip.code}`}</DialogTitle><DialogDescription>{deleting ? 'Perjalanan akan dihapus dari catatan aktif. Perjalanan dengan batch yang sudah diterima tidak dapat dihapus.' : 'Catat batch hasil pendaratan. Kode dibuat berdasarkan perjalanan dan sensor akan langsung mulai memantau.'}</DialogDescription></DialogHeader>{!deleting && <div className="grid max-h-[55dvh] gap-3 overflow-y-auto">{batches.map((batch, index) => <div className="grid grid-cols-[1fr_1fr_1.2fr_auto] gap-2 rounded-lg bg-muted/60 p-3 max-[600px]:grid-cols-1" key={index}><Field label={`Berat batch ${index + 1} (kg)`}><Input type="number" min="0.01" step="0.01" value={batch.weightKg} onChange={(event) => update(index, 'weightKg', event.target.value)} /></Field><Field label="Mutu"><Input value={batch.grade} onChange={(event) => update(index, 'grade', event.target.value)} /></Field><Field label="Sensor"><select className="h-10 rounded-lg border border-input bg-background px-3 text-sm" value={batch.sensorId} onChange={(event) => update(index, 'sensorId', event.target.value)}><option value="">Pilih sensor</option>{availableSensors.map((sensor) => <option disabled={batches.some((item, candidate) => candidate !== index && item.sensorId === sensor.id)} key={sensor.id} value={sensor.id}>{sensor.code}</option>)}</select></Field>{batches.length > 1 && <Button className="self-end" variant="ghost" size="icon" onClick={() => setBatches((current) => current.filter((_, candidate) => candidate !== index))}><Trash2 /><span className="sr-only">Hapus batch</span></Button>}</div>)}<Button variant="outline" onClick={() => setBatches((current) => [...current, { weightKg: '', grade: '', sensorId: '' }])}><Plus />Tambah batch hasil pendaratan</Button></div>}{mutation.isError && <ErrorMessage error={mutation.error} />}<DialogFooter><Button variant="outline" onClick={onClose}>Batal</Button><Button variant={deleting ? 'destructive' : 'default'} onClick={() => mutation.mutate()} disabled={mutation.isPending || !valid}>{deleting ? <Trash2 /> : <Check />}{mutation.isPending ? (deleting ? 'Menghapus…' : 'Menyelesaikan…') : (deleting ? 'Hapus perjalanan' : `Selesaikan dengan ${batches.length.toLocaleString('id-ID')} batch`)}</Button></DialogFooter></DialogContent></Dialog>
}

function TripCard({ trip, onEdit, onComplete, onDelete }) { return <article className="flex flex-col rounded-xl border border-border bg-card p-5 shadow-[0_1px_2px_rgb(2_40_88_/_3%)]" data-trip-card><div className="flex items-start justify-between gap-4"><div className="min-w-0"><h2 className="truncate text-base font-bold">{trip.code}</h2><p className="mt-1 truncate text-xs text-muted-foreground">{trip.vesselName}</p></div><StatusBadge tone={trip.status === 'ACTIVE' ? 'healthy' : 'neutral'}>{trip.status === 'ACTIVE' ? 'Aktif' : 'Selesai'}</StatusBadge></div><dl className="mt-5 divide-y divide-border border-y border-border"><Fact icon={Clock3} label="Dimulai" value={dateTime(trip.startedAt)} /><Fact icon={Check} label="Selesai" value={trip.endedAt ? dateTime(trip.endedAt) : 'Sedang berlangsung'} /><Fact icon={Boxes} label="Batch" value={trip.batchCount.toLocaleString('id-ID')} /></dl><div className="mt-auto pt-4">{trip.status === 'ACTIVE' && <Button className="mb-2 w-full" size="sm" onClick={onComplete}><Check />Selesaikan perjalanan</Button>}<div className="grid grid-cols-2 gap-2"><Button variant="outline" size="sm" onClick={onEdit}><Pencil />Edit</Button><Button variant="destructive-outline" size="sm" onClick={onDelete}><Trash2 />Hapus</Button></div></div></article> }
function Fact({ icon: Icon, label, value }) { return <div className="flex items-center gap-3 py-3 text-xs"><Icon className="shrink-0 text-muted-foreground" size={15} /><dt className="text-muted-foreground">{label}</dt><dd className="ml-auto text-right font-semibold text-foreground">{value}</dd></div> }
function State({ children, error }) { return <div className={`flex min-h-72 flex-col items-center justify-center gap-3 rounded-xl border border-dashed px-5 text-sm ${error ? 'border-red-200 bg-red-50/40 text-red-700' : 'border-slate-300 bg-white/50 text-muted-foreground'}`} role={error ? 'alert' : 'status'}><Anchor size={22} />{children}</div> }

export function FishingTripsPage() {
  const [editing, setEditing] = useState(undefined); const [action, setAction] = useState(null); const [search, setSearch] = useState(''); const [sort, setSort] = useState('startedAt'); const [direction, setDirection] = useState('desc'); const deferredSearch = useDeferredValue(search.trim().toLowerCase()); const query = useQuery({ queryKey: ['fishing-trips'], queryFn: listFishingTrips })
  const trips = (query.data ?? []).filter((trip) => trip.code.toLowerCase().includes(deferredSearch)).toSorted((a, b) => { const left = a[sort] ?? ''; const right = b[sort] ?? ''; return direction === 'asc' ? String(left).localeCompare(String(right), 'id-ID', { numeric: true }) : String(right).localeCompare(String(left), 'id-ID', { numeric: true }) })
  return <div className="mx-auto w-full max-w-[1180px] px-8 pt-12 pb-7 max-[780px]:px-4 max-[780px]:py-6"><PageHeader title="Perjalanan melaut" description="Pantau perjalanan kapal dan batch yang diterima dari setiap pendaratan." action={<Button onClick={() => setEditing(null)}><Plus />Tambah perjalanan</Button>} />{query.isSuccess && query.data.length > 0 && <ListToolbar query={search} onQueryChange={setSearch} sort={sort} onSortChange={setSort} direction={direction} onDirectionChange={setDirection} options={sortOptions} resultCount={trips.length} searchLabel="Cari berdasarkan ID perjalanan" />}{query.isPending && <State>Memuat perjalanan melaut…</State>}{query.isError && <State error>{apiError(query.error)}</State>}{query.isSuccess && !query.data.length && <State>Belum ada perjalanan melaut</State>}{query.isSuccess && query.data.length > 0 && !trips.length && <State>Tidak ada perjalanan yang cocok dengan “{search}”</State>}{trips.length > 0 && <Appear className="grid grid-cols-3 gap-3.5 max-[1020px]:grid-cols-2 max-[640px]:grid-cols-1" stagger="[data-trip-card]">{trips.map((trip) => <TripCard key={trip.id} trip={trip} onEdit={() => setEditing(trip)} onComplete={() => setAction({ trip, action: 'complete' })} onDelete={() => setAction({ trip, action: 'delete' })} />)}</Appear>}{editing !== undefined && <TripDialog trip={editing} onClose={() => setEditing(undefined)} />}{action && <ActionDialog {...action} onClose={() => setAction(null)} />}</div>
}
